// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WsWelcome {
    #[prost(uint64, optional, tag = "1")]
    pub ws_request_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub jwt: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WsInfo {
    #[prost(uint64, optional, tag = "1")]
    pub ws_request_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "3")]
    pub unknown1: ::core::option::Option<bool>,
    #[prost(bytes = "vec", optional, tag = "5")]
    pub unknown2: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "7")]
    pub ws_data: ::core::option::Option<WsData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WsData {
    #[prost(fixed64, optional, tag = "1")]
    pub device_id: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "2")]
    pub message_id: ::core::option::Option<u64>,
    #[prost(message, optional, tag = "3")]
    pub info: ::core::option::Option<ws_data::Info>,
}
/// Nested message and enum types in `WsData`.
pub mod ws_data {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Info {
        #[prost(uint32, optional, tag = "1")]
        pub kind: ::core::option::Option<u32>,
        #[prost(oneof = "info::Data", tags = "29, 61, 63, 77")]
        pub data: ::core::option::Option<info::Data>,
    }
    /// Nested message and enum types in `Info`.
    pub mod info {
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum Kind {
            Unknown = 0,
            Play = 29,
            Device = 61,
            Playing = 63,
            Status = 77,
        }
        impl Kind {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Unknown => "KIND_UNKNOWN",
                    Self::Play => "KIND_PLAY",
                    Self::Device => "KIND_DEVICE",
                    Self::Playing => "KIND_PLAYING",
                    Self::Status => "KIND_STATUS",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "KIND_UNKNOWN" => Some(Self::Unknown),
                    "KIND_PLAY" => Some(Self::Play),
                    "KIND_DEVICE" => Some(Self::Device),
                    "KIND_PLAYING" => Some(Self::Playing),
                    "KIND_STATUS" => Some(Self::Status),
                    _ => None,
                }
            }
        }
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum Data {
            #[prost(message, tag = "29")]
            PlayBlock(super::super::EmptyMessage),
            #[prost(message, tag = "61")]
            DeviceBlock(super::super::ClientBlock),
            #[prost(message, tag = "63")]
            PlayingFor(super::super::StatusBlock),
            #[prost(message, tag = "77")]
            ActiveFor(super::super::StatusBlock),
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EmptyMessage {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StatusBlock {
    #[prost(uint64, optional, tag = "1")]
    pub timestamp_ms: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientBlock {
    #[prost(message, optional, tag = "2")]
    pub details: ::core::option::Option<WsDeviceInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WsDeviceInfo {
    /// 16 bytes
    #[prost(bytes = "vec", optional, tag = "1")]
    pub opaque_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "6")]
    pub platform: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "7")]
    pub caps: ::core::option::Option<Capabilities>,
    #[prost(string, optional, tag = "8")]
    pub app_version: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Capabilities {
    #[prost(uint32, optional, tag = "1")]
    pub a: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub b: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub c: ::core::option::Option<u32>,
}
